name: Build

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_BUILD: cp310-win_amd64

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
